name: Build AWS Image

on:
  workflow_dispatch:

jobs:

  version:
    runs-on: ubuntu-latest
    outputs: 
      version: ${{steps.get-version.outputs.version}}

    defaults:
      run:
        shell: bash

    if: github.ref == 'refs/heads/main'
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Get Version
      id: get-version
      run: |
        VERSION=$(cat versions/sagitta)
        echo "::set-output name=version::$VERSION"

  build-arm-ami:
    needs:
    - version

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      VERSION: ${{ needs.version.outputs.version }}

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: appbricks/vyos-build-ami
        ref: appbricks/dev

    - name: Build ARM AMI
      run: |
        ./vyos-build-ami \
          '{
            "iso": "https://appbricks-public-downloads.s3.amazonaws.com/vyos/vyos-AWS-${VERSION}-arm64.iso",
            "instance_type": "t4g.micro",
            "base_image": {
              "debian_aws_account_id": "379101102735",
              "name": "debian-stretch-hvm-arm64-gp2-*",
              "architecture": "arm64",
              "hypervisor": "xen",
              "root_device_type": "ebs"
            },
            "ami_name": "appbricks-vyos-${VERSION}-arm64",
            "ami_architecture": "arm64"
          }'
